spring:
  datasource:
    url: jdbc:h2:mem:mottu;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

flyway:
  enabled: true
  locations: classpath:db/migration

server:
  port: 8080
